token = "1420455810:AAHhzQFHdUWYu1biyvvYIBqZMLzJss6C7fM"
admin_id = "494861531"

CATEGORY_NAME_ACCOUNTING = "Accounting"
CATEGORY_NAME_CORPORATE_FINANCE = "Corporate finance"
CATEGORY_NAME_ECONOMIC_THEORY = "Economic theory"
CATEGORY_NAME_MANAGEMENT = "Management"

FILE_NAME_ACCOUNTING = "accounting"
FILE_NAME_CORPORATE_FINANCE = "corporate_finance"
FILE_NAME_ECONOMIC_THEORY = "economic_theory"
FILE_NAME_MANAGEMENT = "management"

ALL_CATEGORIES = {
    CATEGORY_NAME_ACCOUNTING: FILE_NAME_ACCOUNTING,
    CATEGORY_NAME_CORPORATE_FINANCE: FILE_NAME_CORPORATE_FINANCE,
    CATEGORY_NAME_ECONOMIC_THEORY: FILE_NAME_ECONOMIC_THEORY,
    CATEGORY_NAME_MANAGEMENT: FILE_NAME_MANAGEMENT,
}